version: "3"
volumes:
  pgdata:
services:
  # web:
  #   build: ../../apps/web
  #   image: rentavid-web
  #   container_name: rentavid-web
  #   expose:
  #     - 8080
  #   ports:
  #     - 8080:3000
  # api:
  #   build: ../../services/api
  #   image: rentavid-api
  #   container_name: rentavid-api
  #   environment:
  #     DB_URL: postgresql://postgres:123456@pagila/postgres
  #   expose:
  #     - 8000
  #   ports:
  #     - 8000:8000
  pagila:
    image: postgres:13.2
    container_name: pagila
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
    volumes:
      - ../../assets/pagila-schema.sql:/docker-entrypoint-initdb.d/1-pagila-schema.sql
      - ../../assets/pagila-data.sql:/docker-entrypoint-initdb.d/2-pagila-data.sql
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
